- checkRoot/checkRoot.js
- getNumberLength/getNumberLength.js
it´s longer then the other guy´s, but any comment are very appreciated. Also sorry for pushing to master yesterday, forgot to fork!
> second attempt

- revertString/revertString.js
This update version of the function revertString can handle more strings inputs.
> Updated version revertMoreStrings

- revertString/revertString.js
Fixed to give consistency between lines of code.
> Updated revertString.js with final style fixes

- sumOfMultiples/README.md
- sumOfMultiples/sumOfMultiples.js
Feel free to critique & comment
> sumOfMultiples Solution

- sumCircle/circle.js
> Function sumCircle Completed

- splitBills/Readme.md
- splitBills/splitBills.js
As per description, adding folder with answer to Splitting Bills exercise. Rest of js folder remains intact.
> adding splitBills folder (including splitBills.js file & readme.md to JS folder)

- new-member-problems/6-countStrings/countStrings.js
- new-member-problems/6-countStrings/readMe.md
I am not sure whether this is all ok - the Github aspects not solution to problem 6. Any feedback appreciated.
> adding new-member-6 solution

- nthChar-function-sol.md
Here's my solution to @philb56's problem!
> new-member-7-entry

- CONTRIBUTING.md
Added short section about contributing to the repo (i.e. making changes or suggestions)
> added section on contributing

- new-member-problems/13-tube-strike-opts-calc/README.md
- new-member-problems/13-tube-strike-opts-calc/tube-strike-opts-calc.js
@matthewglover completed the challenge. Merging with master branch.
> New member tube strike opts calc

- new-member-problems/16-multiFilter/README.md
- new-member-problems/16-multiFilter/multiFilter.js
added multiFilter function for new-member-16
> multiFilter

- new-member-problems/17 - greatestDifference/README.md
- new-member-problems/17 - greatestDifference/greatestDifference.js
Solution to greatest difference kata for someone to check and merge.
> Greatest difference

- new-member-problems/19-self-descriptive-numbers/README.md
- new-member-problems/19-self-descriptive-numbers/self-desriptive-number.js
This is solution to https://github.com/codingforeveryone/js/issues/90
> solution to new-member-19

- new-member-21-solution
I have created two functions, one to find the divisors of an integer, the other to check if that integer is abundant, deficient or perfect.
I have called them for both arguments in the main function deficientlyAbundantAmicableNumbers(num1, num2).
I have pushed the results in an array and returned it as a string.
I realise that using an array is not mandatory in this case, but I like working with arrays when I can as I find them easier to read and modify.
Since it is the first time I'm using GitHub, I hope I am following the guidelines accordingly, please let me know if there is something I should have done differently.
Thanks!
> New Member-21 - my solution

- new-member-problems/22-sum-largest-pair/pairsum.js
> Problem 22

- new-member-problems/23-move-vowels/moveVowel.js
> Add moveVowel function

- new-member-problems/24-Take-a-ten-minute-walk/24-Take-a-ten-minute-walk.js
hey @RichAWarren, here is my proposition, would be awesome to hear what you think!
:)
> my proposition of the kata Ten Minutes Walk

- new-member-problems/Solution for Paperboy.js
Solution for new-member-27 Paperboy
> Solution-27 Paperboy

- new-member-problems/Between Extremes_Solution.js
Solution for new-member-25 Between Extremes
> Solution-25 Between Extremes

- new-member-problems/31-conference traveler/README.md
- new-member-problems/31-conference traveler/conference-traveler.js
> conference traveler

- new-member-problems/33-amountToCoins/amountToCoins.js
Added a solution for juliankolbe's issue 'Amount to coins' (#116).
> Added solution for new-member-33: Amount to coins
